### ISSUE TITLE
arm64 deploy is failing (in Kubespray)?

### ISSUE THREAD

**Issue by vielmetti** [crosscloudci/ci-dashboard#151]
The deploy stage on the arm64 setup is failing. 

Here is the failure message, suggesting that it's pointing at a machine that's down:

```
TASK [bootstrap-os : Fetch /etc/os-release] ************************************
ok: [node1]
fatal: [node0]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 139.178.89.62 port 22: Connection timed out", "unreachable": true}
```

This from the log file at https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/198264

Happy to help untangle the dependencies here to get this back to green!

**Comment by vielmetti** [comment]
The IP address in the log reverses to  `arm64stable-pd-master1`

**Comment by lixuna** [comment]
Thank you for reporting this, @vielmetti 

On Friday, we rebooted the 'arm64stable-pd-master1' machine. K8s Stable + Arm provisioning is currently working as expected on cncf.ci, see https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/199429

Today, we will reboot the machine used for K8s HEAD + Arm to resolve the unreachable error in https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/199437
