### ISSUE TITLE
Rebrand "Packet" as "Equinix Metal"

### ISSUE THREAD

**Issue by vielmetti** [crosscloudci/ci-dashboard#184]
Packet has rebranded itself after an acquisition by Equinix as "Equinix Metal".

There's a piece of the UI at https://github.com/crosscloudci/ci-dashboard/blob/65aef2d1b97ff58c48807d090d989e70b7ac4d51/src/components/TestEnvironment.vue#L54-L59 (or thereabouts) with the Packet logo and link. This should be updated appropriately.

**Comment by lixuna** [comment]
Thank you, @vielmetti 

Do you happen to have access to an Equinix Metal logo, as svg with transparent background?

**Comment by lixuna** [comment]
Please disregard, @vielmetti 

We should be able to use the logo at https://landscape.cncf.io/logos/equinix-metal-member.svg

**Comment by lixuna** [comment]
Here is a stacked svg that may also work on cncf.ci https://landscape.lfedge.org/logos/equinix-metal-member.svg

**Comment by agentpoyo** [comment]
Troubleshooting the following error seen in integration environment while testing the new logo and link changes to equinix metal.

```
Error: error installing: Post https://api.prod.cluster.cncf.ci/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp 54.252.198.248:443: i/o timeout
ERROR: Job failed: exit code 1
```

**Comment by agentpoyo** [comment]
The AWS api.prod master was deleted by Amazon. We're in the process of deploying a new dashboard cluster.

**Comment by agentpoyo** [comment]
New logo on desktop in Chrome:

![quinix_logo_update](https://user-images.githubusercontent.com/14348948/98420295-7eb00400-204c-11eb-87c5-ea59d632db61.png)

@lixuna

**Comment by agentpoyo** [comment]
Mobile screenshot of new Equinix screenshot:

![mobile_equinix_update](https://user-images.githubusercontent.com/14348948/98420620-347b5280-204d-11eb-9379-dfdf82b70d3c.png)

**Comment by agentpoyo** [comment]
https://cidev.cncf.ci is reflecting the new logo. If everyone agrees this is good, we can push out to the other environments. @lixuna @vielmetti @taylor

**Comment by vielmetti** [comment]
Looks good to me, thanks @agentpoyo

**Comment by lixuna** [comment]
Looks good, @agentpoyo Thanks!

**Comment by agentpoyo** [comment]
Excellent. I'll work on getting this pushed up through the environments.

**Comment by agentpoyo** [comment]
IE with new logo:

![windows_ie_cidev_equinix_metal](https://user-images.githubusercontent.com/14348948/98565384-2d358e00-2273-11eb-839e-6731feeff451.JPG)

**Comment by agentpoyo** [comment]
The changes have been pushed through to production. Production will reflect tomorrow as the dashboard is scheduled to run nightly.

https://dev.cncf.ci and https://staging.cncf.ci both reflect the new logo (along with the new cluster).

**Comment by agentpoyo** [comment]
Changes have been pushed through to prod. Screenshot of the prod https://cncf.ci dashboard:

![cncf_prod_newloo](https://user-images.githubusercontent.com/14348948/98681876-d8ece580-2328-11eb-9566-00445315a536.png)
