### ISSUE TITLE
Redirect cncf.ci to https://github.com/crosscloudci/crosscloudci

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/ci-dashboard#207]
**Please redirect cncf.ci to https://github.com/crosscloudci/crosscloudci**

- CI Status dashboard is on hold
- TLS Certificate has expired on 2nd Feb

Tasks:

- [x]  redirect url to github project

**Comment by agentpoyo** [comment]
The redirect is in place. @lixuna

**Comment by lixuna** [comment]
thank you, @agentpoyo and @denverwilliams 

I was able to see the redirect on an incognito window. Thanks!
