### ISSUE TITLE
Delete resources used for cncf.ci

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/ci-dashboard#208]
**Delete resources used for cncf.ci**

- CI Status dashboard is on hold

Tasks:

- [x] Backup any data that is not stored in GitHub
- [x] Plan/list which resources to delete
- [x] Add comment in this issue with status update of which resources are deleted and which resources will be kept and why
- [x] Communicate externally that the deleted resources can be repurposed elsewhere

**Comment by agentpoyo** [comment]
![metal_resource_list_for_cncfci](https://user-images.githubusercontent.com/14348948/153657708-ad112526-b9c8-4d2a-aebe-e050f726bbf9.png)

**Comment by agentpoyo** [comment]
```
[ci-dashboard-prod-master1](https://console.equinix.com/devices/592a887e-8ff1-4730-a622-4290f03b9268)
x1.small.x86	147.75.195.115	On Demand	
ubuntu logo
NY - EWR1	
	
[ci-dashboard-prod-master2](https://console.equinix.com/devices/6b98044d-3b30-413a-8868-a45263cf592e)
x1.small.x86	147.75.67.103	On Demand	
ubuntu logo
NY - EWR1	
	
[ci-dashboard-prod-master3](https://console.equinix.com/devices/0797cc45-a3a6-42cd-ab2f-a54d047c5543)
x1.small.x86	147.75.38.75	On Demand	
ubuntu logo
NY - EWR1	
	
[ci-dashboard-prod-worker1](https://console.equinix.com/devices/724cb602-c1c6-4dea-a1eb-ec8ae851dcff)
c2.medium.x86	147.75.195.118	On Demand	
ubuntu logo
NY - EWR1	
	
[runner.cncf.ci](https://console.equinix.com/devices/a03ca1e6-94fc-4739-81f9-d2552edcc1e7)
m1.xlarge.x86	139.178.69.61	On Demand	
debian logo
SV - SJC1	
	
[runner.cncf.ci-arm](https://console.equinix.com/devices/f9baef23-1c6a-47d6-9cf4-edc4b640da7f)
c2.large.arm	147.75.38.162	On Demand	
debian logo
NY - EWR1
```

**Comment by agentpoyo** [comment]
The gitlab server can be deleted as well as it's under the CNCF Sandbox project and not the CNCF CI project.

```
gitlab.cncf.ci | m1.xlarge.x86 | 147.75.69.97 | On Demand |   | SV - SJC1

[gitlab.cncf.ci](https://console.equinix.com/devices/10d4f228-e7d5-4bfe-9f4f-56d176865bd4)
m1.xlarge.x86	147.75.69.97	On Demand	
debian logo
SV - SJC1
```

**Comment by agentpoyo** [comment]
@lixuna all of the listed servers above that were part of the cncf.ci dashboard have been turned off. After a few days, we should be able to terminate these.

**Comment by agentpoyo** [comment]
All shutdown resources have been terminated.

**Comment by lixuna** [comment]
email sent

**Comment by lixuna** [comment]
To Do: 
- delete 5 remaining systems in the "CNCF CI" project, with names cnftestbed-{master,worker}{1,2,3}

**Comment by lixuna** [comment]
A/C passes:
- all systems have been deleted under the CI project
