### ISSUE TITLE
Last updated automatically shows null may be after couple of minute

### ISSUE THREAD

**Issue by sasachan** [crosscloudci/ci-dashboard#72]
Based of SIG meeting, I was navigating the dashboard at 'https://cncf.ci/'. At the time page load everything seems okay. However, may be within couple of minute Last updated shows value as Null.
![LastUpdateShowsNull](https://user-images.githubusercontent.com/12516416/54333043-da8f7300-4646-11e9-8e51-0261dfe807cb.jpg)

**Comment by lixuna** [comment]
Thank you, @sasachan - we are investigating this issue in ticket https://github.com/crosscloudci/crosscloudci/issues/123 (status: in progress).

**Comment by lixuna** [comment]
closing this ticket as duplicate of https://github.com/crosscloudci/crosscloudci/issues/123
